[project]
name = "behringer-xr18-control-x-touch-mini"
version = "0.1.0"
description = "daemon to control xr18 with x-touch mini"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mido>=1.3.3",
    "python-rtmidi>=1.5.8",
    "sounddevice>=0.5.1",
    "soundfile>=0.13.1",
    "winotify>=1.1.0; sys_platform == 'win32'",
]
